"""
Events Module
Events, campaigns, and activities management for VCK platform.
"""

from src.events.models import (
    Event,
    EventAttendance,
    EventTask,
    EventBudget,
    EventFeedback,
    Campaign,
    CampaignTask,
    EventType,
    EventStatus,
    AttendanceStatus,
    TaskStatus,
    CampaignStatus,
)
from src.events.schemas import (
    EventCreate,
    EventUpdate,
    EventResponse,
    EventDetailResponse,
    EventListResponse,
    EventSearchFilters,
    EventTaskCreate,
    EventTaskUpdate,
    EventTaskResponse,
    EventAttendanceCreate,
    EventAttendanceResponse,
    EventFeedbackCreate,
    EventFeedbackResponse,
    EventBudgetCreate,
    EventBudgetResponse,
    EventStats,
    EventStatsResponse,
    CampaignCreate,
    CampaignUpdate,
    CampaignResponse,
    CampaignTaskCreate,
    CampaignTaskUpdate,
    CampaignTaskResponse,
)
from src.events.crud import (
    EventCRUD,
    EventAttendanceCRUD,
    EventTaskCRUD,
    EventBudgetCRUD,
    EventFeedbackCRUD,
    EventStatsCRUD,
    CampaignCRUD,
    CampaignTaskCRUD,
)
from src.events.router import router as events_router

__all__ = [
    # Models
    "Event",
    "EventAttendance",
    "EventTask",
    "EventBudget",
    "EventFeedback",
    "Campaign",
    "CampaignTask",
    "EventType",
    "EventStatus",
    "AttendanceStatus",
    "TaskStatus",
    "CampaignStatus",
    # Schemas
    "EventCreate",
    "EventUpdate",
    "EventResponse",
    "EventDetailResponse",
    "EventListResponse",
    "EventSearchFilters",
    "EventTaskCreate",
    "EventTaskUpdate",
    "EventTaskResponse",
    "EventAttendanceCreate",
    "EventAttendanceResponse",
    "EventFeedbackCreate",
    "EventFeedbackResponse",
    "EventBudgetCreate",
    "EventBudgetResponse",
    "EventStats",
    "EventStatsResponse",
    "CampaignCreate",
    "CampaignUpdate",
    "CampaignResponse",
    "CampaignTaskCreate",
    "CampaignTaskUpdate",
    "CampaignTaskResponse",
    # CRUD
    "EventCRUD",
    "EventAttendanceCRUD",
    "EventTaskCRUD",
    "EventBudgetCRUD",
    "EventFeedbackCRUD",
    "EventStatsCRUD",
    "CampaignCRUD",
    "CampaignTaskCRUD",
    # Router
    "events_router",
]
