"""
Grievances Module
Comprehensive grievance management for the VCK platform.
"""

from src.grievances.models import (
    Grievance,
    GrievanceCategory,
    GrievanceAssignment,
    GrievanceEscalation,
    GrievanceSLA,
    GrievanceResolution,
    GrievanceStatus,
    GrievancePriority,
    GrievanceCategoryType,
    AssignmentType,
    EscalationLevel,
)

from src.grievances.schemas import (
    GrievanceCreate,
    GrievanceUpdate,
    GrievanceResponse,
    GrievanceDetailResponse,
    GrievanceListResponse,
    GrievanceSearchFilters,
    GrievanceCategoryCreate,
    GrievanceCategoryUpdate,
    GrievanceCategoryResponse,
    GrievanceCategoryListResponse,
    GrievanceAssignmentCreate,
    GrievanceAssignmentClaim,
    GrievanceAssignmentResponse,
    GrievanceAssignmentHistoryResponse,
    GrievanceEscalationCreate,
    GrievanceEscalationResponse,
    GrievanceSLAResponse,
    GrievanceSLAStatus,
    GrievanceResolutionCreate,
    GrievanceResolutionUpdate,
    GrievanceResolutionResponse,
    GrievanceStats,
    GrievanceStatsResponse,
    GrievanceDashboard,
    GrievanceDashboardResponse,
    GrievanceAcknowledge,
    GrievanceInvestigate,
    GrievanceResolve,
    GrievanceClose,
    GrievanceReopen,
    GrievanceReject,
    GrievanceSubmitFeedback,
)

from src.grievances.crud import (
    GrievanceCRUD,
    GrievanceCategoryCRUD,
    GrievanceWorkflowCRUD,
    GrievanceAssignmentCRUD,
    GrievanceEscalationCRUD,
    GrievanceSLACRUD,
    GrievanceResolutionCRUD,
    GrievanceStatsCRUD,
)

from src.grievances.router import router as grievances_router

__all__ = [
    # Models
    "Grievance",
    "GrievanceCategory",
    "GrievanceAssignment",
    "GrievanceEscalation",
    "GrievanceSLA",
    "GrievanceResolution",
    "GrievanceStatus",
    "GrievancePriority",
    "GrievanceCategoryType",
    "AssignmentType",
    "EscalationLevel",
    # Schemas
    "GrievanceCreate",
    "GrievanceUpdate",
    "GrievanceResponse",
    "GrievanceDetailResponse",
    "GrievanceListResponse",
    "GrievanceSearchFilters",
    "GrievanceCategoryCreate",
    "GrievanceCategoryUpdate",
    "GrievanceCategoryResponse",
    "GrievanceCategoryListResponse",
    "GrievanceAssignmentCreate",
    "GrievanceAssignmentClaim",
    "GrievanceAssignmentResponse",
    "GrievanceAssignmentHistoryResponse",
    "GrievanceEscalationCreate",
    "GrievanceEscalationResponse",
    "GrievanceSLAResponse",
    "GrievanceSLAStatus",
    "GrievanceResolutionCreate",
    "GrievanceResolutionUpdate",
    "GrievanceResolutionResponse",
    "GrievanceStats",
    "GrievanceStatsResponse",
    "GrievanceDashboard",
    "GrievanceDashboardResponse",
    "GrievanceAcknowledge",
    "GrievanceInvestigate",
    "GrievanceResolve",
    "GrievanceClose",
    "GrievanceReopen",
    "GrievanceReject",
    "GrievanceSubmitFeedback",
    # CRUD
    "GrievanceCRUD",
    "GrievanceCategoryCRUD",
    "GrievanceWorkflowCRUD",
    "GrievanceAssignmentCRUD",
    "GrievanceEscalationCRUD",
    "GrievanceSLACRUD",
    "GrievanceResolutionCRUD",
    "GrievanceStatsCRUD",
    # Router
    "grievances_router",
]
