"""
Members Module
Member management for the VCK political party platform.
"""

from src.members.models import (
    Member,
    MemberProfile,
    MemberFamily,
    MemberDocument,
    MemberNote,
    MembershipHistory,
    MemberTagDefinition,
    MemberSkillDefinition,
    MembershipStatus,
    MembershipType,
    Gender,
    DocumentType,
    RelationshipType,
)
from src.members.schemas import (
    MemberCreate,
    MemberUpdate,
    MemberResponse,
    MemberDetailResponse,
    MemberListResponse,
    MemberSearchFilters,
    MemberProfileCreate,
    MemberProfileUpdate,
    MemberProfileResponse,
    MemberFamilyCreate,
    MemberFamilyUpdate,
    MemberFamilyResponse,
    MemberDocumentCreate,
    MemberDocumentResponse,
    MemberTagAdd,
    MemberTagResponse,
    MemberNoteCreate,
    MemberNoteUpdate,
    MemberNoteResponse,
    MembershipHistoryResponse,
    MemberStats,
    MemberStatsResponse,
    MemberBulkImport,
    MemberBulkImportResult,
    MemberExportRequest,
)
from src.members.crud import (
    MemberCRUD,
    MemberProfileCRUD,
    MemberFamilyCRUD,
    MemberDocumentCRUD,
    MemberNoteCRUD,
    MemberTagCRUD,
    MemberStatsCRUD,
    MemberBulkCRUD,
)
from src.members.router import router as members_router

__all__ = [
    # Models
    "Member",
    "MemberProfile",
    "MemberFamily",
    "MemberDocument",
    "MemberNote",
    "MembershipHistory",
    "MemberTagDefinition",
    "MemberSkillDefinition",
    "MembershipStatus",
    "MembershipType",
    "Gender",
    "DocumentType",
    "RelationshipType",
    # Schemas
    "MemberCreate",
    "MemberUpdate",
    "MemberResponse",
    "MemberDetailResponse",
    "MemberListResponse",
    "MemberSearchFilters",
    "MemberProfileCreate",
    "MemberProfileUpdate",
    "MemberProfileResponse",
    "MemberFamilyCreate",
    "MemberFamilyUpdate",
    "MemberFamilyResponse",
    "MemberDocumentCreate",
    "MemberDocumentResponse",
    "MemberTagAdd",
    "MemberTagResponse",
    "MemberNoteCreate",
    "MemberNoteUpdate",
    "MemberNoteResponse",
    "MembershipHistoryResponse",
    "MemberStats",
    "MemberStatsResponse",
    "MemberBulkImport",
    "MemberBulkImportResult",
    "MemberExportRequest",
    # CRUD
    "MemberCRUD",
    "MemberProfileCRUD",
    "MemberFamilyCRUD",
    "MemberDocumentCRUD",
    "MemberNoteCRUD",
    "MemberTagCRUD",
    "MemberStatsCRUD",
    "MemberBulkCRUD",
    # Router
    "members_router",
]
