"""
Communications Module
Handles announcements, forums, posts, comments, and grievances.
"""

from src.communications.models import (
    Announcement,
    AnnouncementTarget,
    Forum,
    ForumPost,
    ForumComment,
    ForumReaction,
    ForumGrievance,
    GrievanceUpdate,
    GrievanceAttachment,
    CommunicationLog,
    AnnouncementScope,
    AnnouncementType,
    ForumVisibility,
    GrievanceStatus,
    GrievancePriority,
    CommunicationChannel,
    ReactionType,
)

from src.communications.schemas import (
    AnnouncementCreate,
    AnnouncementUpdate,
    AnnouncementResponse,
    AnnouncementListResponse,
    AnnouncementDetailResponse,
    ForumCreate,
    ForumUpdate,
    ForumResponse,
    ForumListResponse,
    ForumDetailResponse,
    ForumPostCreate,
    ForumPostUpdate,
    ForumPostResponse,
    ForumPostListResponse,
    ForumPostDetailResponse,
    ForumPostModeration,
    ForumCommentCreate,
    ForumCommentUpdate,
    ForumCommentResponse,
    ForumCommentListResponse,
    ForumReactionCreate,
    GrievanceCreate,
    GrievanceUpdate,
    GrievanceResponse,
    GrievanceListResponse,
    GrievanceDetailResponse,
    GrievanceStatusUpdate,
    GrievanceTicketResponse,
    CommunicationStats,
    AnnouncementStats,
    ForumStats,
    GrievanceStats,
)

from src.communications.crud import (
    AnnouncementCRUD,
    ForumCRUD,
    ForumPostCRUD,
    ForumCommentCRUD,
    ForumReactionCRUD,
    ForumGrievanceCRUD,
    CommunicationLogCRUD,
    CommunicationStatsCRUD,
)

from src.communications.router import router as communications_router

__all__ = [
    # Models
    "Announcement",
    "AnnouncementTarget",
    "Forum",
    "ForumPost",
    "ForumComment",
    "ForumReaction",
    "ForumGrievance",
    "GrievanceUpdate",
    "GrievanceAttachment",
    "CommunicationLog",
    "AnnouncementScope",
    "AnnouncementType",
    "ForumVisibility",
    "GrievanceStatus",
    "GrievancePriority",
    "CommunicationChannel",
    "ReactionType",
    
    # Schemas
    "AnnouncementCreate",
    "AnnouncementUpdate",
    "AnnouncementResponse",
    "AnnouncementListResponse",
    "AnnouncementDetailResponse",
    "ForumCreate",
    "ForumUpdate",
    "ForumResponse",
    "ForumListResponse",
    "ForumDetailResponse",
    "ForumPostCreate",
    "ForumPostUpdate",
    "ForumPostResponse",
    "ForumPostListResponse",
    "ForumPostDetailResponse",
    "ForumPostModeration",
    "ForumCommentCreate",
    "ForumCommentUpdate",
    "ForumCommentResponse",
    "ForumCommentListResponse",
    "ForumReactionCreate",
    "GrievanceCreate",
    "GrievanceUpdate",
    "GrievanceResponse",
    "GrievanceListResponse",
    "GrievanceDetailResponse",
    "GrievanceStatusUpdate",
    "GrievanceTicketResponse",
    "CommunicationStats",
    "AnnouncementStats",
    "ForumStats",
    "GrievanceStats",
    
    # CRUD
    "AnnouncementCRUD",
    "ForumCRUD",
    "ForumPostCRUD",
    "ForumCommentCRUD",
    "ForumReactionCRUD",
    "ForumGrievanceCRUD",
    "CommunicationLogCRUD",
    "CommunicationStatsCRUD",
    
    # Router
    "communications_router",
]
